package smartcookerDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.smartcooker.app.dal.model.LocalRecipeListModel;
import com.example.smartcooker.app.dal.model.RecipeDetailModel;

import smartcookerDao.LocalRecipeListModelDao;
import smartcookerDao.RecipeDetailModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localRecipeListModelDaoConfig;
    private final DaoConfig recipeDetailModelDaoConfig;

    private final LocalRecipeListModelDao localRecipeListModelDao;
    private final RecipeDetailModelDao recipeDetailModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localRecipeListModelDaoConfig = daoConfigMap.get(LocalRecipeListModelDao.class).clone();
        localRecipeListModelDaoConfig.initIdentityScope(type);

        recipeDetailModelDaoConfig = daoConfigMap.get(RecipeDetailModelDao.class).clone();
        recipeDetailModelDaoConfig.initIdentityScope(type);

        localRecipeListModelDao = new LocalRecipeListModelDao(localRecipeListModelDaoConfig, this);
        recipeDetailModelDao = new RecipeDetailModelDao(recipeDetailModelDaoConfig, this);

        registerDao(LocalRecipeListModel.class, localRecipeListModelDao);
        registerDao(RecipeDetailModel.class, recipeDetailModelDao);
    }
    
    public void clear() {
        localRecipeListModelDaoConfig.clearIdentityScope();
        recipeDetailModelDaoConfig.clearIdentityScope();
    }

    public LocalRecipeListModelDao getLocalRecipeListModelDao() {
        return localRecipeListModelDao;
    }

    public RecipeDetailModelDao getRecipeDetailModelDao() {
        return recipeDetailModelDao;
    }

}
